apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasource
  labels:
    app: grafana
    chart: grafana-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: {{ .Values.datasources.prometheus.type }}
      url: {{ .Values.datasources.prometheus.url }}
      access: {{ .Values.datasources.prometheus.access }}
      basicAuth: {{ .Values.datasources.prometheus.basicAuth }}
      editable: {{ .Values.datasources.prometheus.editable }}
      isDefault: {{ .Values.datasources.prometheus.isDefault }}