apiVersion: v2
name: cash-service
description: cash-service
version: 0.2.0
dependencies:
  - name: accounts-service
    version: "0.1.0"
    repository: "file://charts/accounts-service"
  - name: notification-service
    version: "0.3.0"
    repository: "file://charts/notification-service"