apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: elasticsearch-secrets
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data-volume
      volumes:
        - name: es-data-volume
          persistentVolumeClaim:
            claimName: es-persistent-storage