spring:
  application:
    name: cash-service

  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/bank-realm

    client:
      registration:
        cash-service:
          provider: keycloak
          client-id: cash-service
          client-secret: vyaCq9VeSNIEwP84quDZbmX0rMzEPYLc
          authorization-grant-type: client_credentials
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/realms/bank-realm

server:
  port: 8082

# Kafka
topic:
  name: cash-events
bootstrap:
  servers: ${BOOTSTRAP_SERVERS}
acks: ${ACKS}
retries: ${RETRIES}