spring:
  application:
    name: cash-service

  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/bank-realm

    client:
      registration:
        cash-service:
          provider: keycloak
          client-id: cash-service
          client-secret: vyaCq9VeSNIEwP84quDZbmX0rMzEPYLc
          authorization-grant-type: client_credentials
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/realms/bank-realm
  management:
    management:
      zipkin:
        tracing:
          endpoint: http://127.0.0.1:9411/api/v2/spans
      tracing:
        sampling:
          probability: 1
    endpoints:
      web:
        exposure:
          include: metrics, prometheus

server:
  port: 8082

# Kafka
topic:
  name: cash-events
bootstrap:
  servers: ${BOOTSTRAP_SERVERS}
acks: ${ACKS}
retries: ${RETRIES}