apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-zipkin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-zipkin
    spec:
      containers:
          - name: zipkin
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: {{ .Values.service.port }}
            env:
              - name: JAVA_OPTS
                value: "-Dserver.port={{ .Values.service.port }}"