spring:
  application:
    name: notifications-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

      client:
        registration:
          notification-service:
            provider: keycloak
            client-id: notification-service
            client-secret: 7pdLamuTXlSlSjJWz7Hw2CeCOezTx7Bq
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm

  kafka:
    bootstrap-servers: kafka-broker-0.kafka-headless.default.svc.cluster.local:9092
    consumer:
      group-id: notification
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  management:
    zipkin:
      tracing:
        endpoint: http://127.0.0.1:9411/api/v2/spans
    tracing:
      sampling:
        probability: 1

#  cloud:
#    zookeeper:
#      connect-string: localhost:2181
#      discovery:
#        enabled: true
#      config:
#        enabled: true

server:
  port: 8084

page:
  limit: 5

app:
  rmq-limit: 5

#routing-key:
#  account: accountRK
#  transfer: transferRK
#  cash: cashRK

# Kafka
bootstrap:
  servers: ${BOOTSTRAP_SERVERS}
group:
  id: ${GROUP_ID}
auto:
  offset:
    reset: ${AUTO_OFFSET_RESET}
