apiVersion: v2
name: umbrella-chart
description: An umbrella Helm chart to deploy accounts, cash, notification and transfer services
version: 1.0.0
dependencies:
  - name: accounts-service
    version: "0.1.0"
    repository: "file://charts/accounts-service"
  - name: cash-service
    version: "0.2.0"
    repository: "file://charts/cash-service"
  - name: notification-service
    version: "0.3.0"
    repository: "file://charts/notification-service"
  - name: transfer-service
    version: "0.4.0"
    repository: "file://charts/transfer-service"
  - name: database-service
    version: "0.5.0"
    repository: "file://charts/database-service"
  - name: grafana
    version: 0.6.0
    repository: "file://charts/grafana"
  - name: prometheus
    version: 0.7.0
    repository: "file://charts/prometheus"