spring:
  application:
    name: accounts-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  cloud:
#    zookeeper:
#      connect-string: localhost:2181
#      discovery:
#        enabled: true
#      config:
#        enabled: true

  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/bank-realm

    client:
      registration:
        account-service:
          provider: keycloak
          client-id: account-service
          client-secret: tXqLhkxAOcWh1QiVrvLoT1hoi6nnwoHe
          authorization-grant-type: client_credentials
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/realms/bank-realm

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/scripts/db.changelog-master.xml

  management:
    zipkin:
      tracing:
        endpoint: http://127.0.0.1:9411/api/v2/spans
    tracing:
      sampling:
        probability: 1
    endpoints:
      web:
        exposure:
          include: metrics, prometheus

server:
  port: 8081

topic:
  name: account-events

# Kafka
bootstrap:
  servers: ${BOOTSTRAP_SERVERS}
acks: ${ACKS}
retries: ${RETRIES}