apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-service.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}-container
              image: {{ .Values.image.repository }}
              ports:
                - containerPort: 8081
              env:
                  - name: DB_NAME
                    valueFrom:
                      configMapKeyRef:
                        name: database-config
                        key: database
                  - name: POSTGRES_USER
                    valueFrom:
                      configMapKeyRef:
                        name: database-config
                        key: username
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      configMapKeyRef:
                        name: database-config
                        key: password
                  - name: DB_HOST
                    valueFrom:
                      configMapKeyRef:
                        name: database-config
                        key: host
                  - name: DB_PORT
                    valueFrom:
                      configMapKeyRef:
                        name: database-config
                        key: port
                  - name: ACKS
                    mountPath: { { .Values.global.producerConfig.acks } }
                  - name: RETRIES
                    mountPath: { { .Values.global.producerConfig.retries } }
